#!/usr/bin/env python3
"""Read CPU and GPU voltage from BC-250 SMU."""

import sys

def main():
    try:
        from bc250_smu import Bc250Smu
    except ImportError:
        print("Error: bc250_smu not installed. Install with:", file=sys.stderr)
        print("  git clone https://github.com/bc250-collective/bc250_smu_oc.git", file=sys.stderr)
        print("  cd bc250_smu_oc && pip install .", file=sys.stderr)
        sys.exit(1)

    smu = Bc250Smu()
    try:
        if len(sys.argv) > 1 and sys.argv[1] == "gpu":
            print(smu.q3_0x37_get_current_gpu_voltage())
        else:
            print(smu.q3_0x36_get_current_cpu_voltage())
    finally:
        smu.close()

if __name__ == "__main__":
    main()
